### ISSUE TITLE
Replace `assert` with `Raise SomeError`

### ISSUE THREAD

**Issue by dennlinger** [tannonk/llm_inference#2]
One of my nitpicks in Python code is that `assert` statements may not be run if running with the `python -O` flag. Although unlikely, better practice is to replace them with `raise SomeError("")`, which always triggers.  
This simultaneously forces us to write some (more or less specific) error codes as well, such that ideally users have a clear idea *why* code failed.

**Comment by tannonk** [comment]
Thanks for the tip! Done in 61c19b9.
