### ISSUE TITLE
[Potential Bug] Typing incomaptibility in util functions

### ISSUE THREAD

**Issue by dennlinger** [tannonk/llm_inference#5]
Hi,  
just noticed that there is a potential type conflict between `serialize_to_jsonl` (expects a `List[str]` as the second input, and the output of `postprocess_model_outputs` (`List[List[str]]`).
This is relevant for line 107 in `inference.py`, but not sure if this is just a potential mistake on the coding end, or could actually cause an error when running the script.

**Comment by tannonk** [comment]
Good spotting! This is now updated in fc0d729 to reflect the actual expected type.
