### ISSUE TITLE
Sample `prompts/p0.json`

### ISSUE THREAD

**Issue by dennlinger** [tannonk/llm_inference#6]
The example script to run the `inference.py` file lists a `prompts/p0.json` file path, which does not seem to be included in the installation instructions. I have run `scripts/fetch_data.sh/` script, but still nothing.

Would it be possible to share this as a dummy script to let users build on top of this template?

**Comment by tannonk** [comment]
Do you mean this one: https://github.com/tannonk/llm_inference/blob/main/prompts/p0.json? It should be available on main.

**Comment by dennlinger** [comment]
Sorry, my bad. I think my local branch was behind `main`, which is why I already saw the updated CLI argument, but not yet the `json`. Thanks for clarifying!
